version: '3.1'

services:
  mongo:
    image: mongo
    container_name: node-workshop
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    links:
      - mongo
